### ISSUE TITLE
Buttons requested

### ISSUE THREAD

**Issue by kgold2** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#23] opened 2020-06-22 21:20 UTC
Build: Equivalent to C-S-B <RET>
Run: Equivalent to C-F5
Debug: Equivalent to F5

**Comment by scotthardwick** [comment] 2020-09-16 20:03
Build - workbench.action.tasks.build
Run - workbench.action.debug.run
Debug - workbench.action.debug.start or workbench.action.debug.continue... F5 chooses between them depending on value of inDebugMode

**Comment by GorvGoyl** [comment] 2020-09-19 08:09
Duplicate of #14

**Closed** 2020-09-19 08:10 UTC
Labels: button request
